/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "+Infinity": "+无限",
    "Amount:": "数量:",
    "Cancel": "取消",
    "Change Log": "更新日志",
    "Growths:": "成长:",
    "Scientific": "科学",
    "Max All": "全部最大",
    "Exit": "退出",
    "Currently:": "当前:",
    "Confirm": "确认",
    "boost × (10 / rate)": "提升 × (10 / 率)",
    ", and your best is": "，你最好的是",
    "\"A Zillion?\": Reach a Number of": "\"A Zillion?\"：达到一定数量",
    "\"ADDICTED\": Play for 10 days.": "\"ADDICTED\"：玩了 10 天。",
    "\"Coming back for more\": Come back to the game after 8 hours of offline time.": "\"回来获取更多\"：离线 8 小时后返回游戏。",
    "\"Does this work?\": Multiplier Prestige for the 1st time.": "\“这有效吗？\”：第一次乘数声望。",
    "\"Hey where'd my progress go\": Product for the 1st time.": "“嘿，我的进步去哪儿了”：第一次产品。",
    "\"Many Multipliers\": Have at least 50 total Multipliers.": "\“许多乘数”：至少有 50 个总乘数。",
    "\"Multiplying Multipliers\": Make all Multipliers reach x": "\"Multiplying Multipliers\": 使所有乘数达到 x",
    "\"Ok Google\": Reach": "\"Ok Google\"：到达",
    "\"Welcome\": Buy your first Multiplier.": "\"欢迎\"：购买你的第一个乘数。",
    "):\n          Requires": "):\n 需要",
    "Achivement Unlocked: \"No easter egg here\"!": "成就解锁：“这里没有复活节彩蛋”！",
    "Additive": "附加",
    "Auto-Save Rate:": "自动保存频率：",
    "Convert all your Multipliers into a new currency.": "将所有乘数转换为新货币。",
    "Costs": "成本",
    "Do a Multiplier Prestige": "进行乘数声望",
    "Don't even bother clicking below this text.": "甚至不必费心单击此文本下方。",
    "Factor Upgrades": "因子升级",
    "Factored Points": "因子点数",
    "Factored Points boost Number production.": "Factored Points 可促进数字生产。",
    "FP in total.": "FP总计。",
    "Implementing soon!": "即将实施！",
    "Import your save here:": "在此处导入您的保存：",
    "Infinity days, Infinity hours, Infinity minutes and Infinity seconds": "无限天、无限小时、无限分钟和无限秒",
    "Multiplier 1 is 10% stronger, Multiplier 9 is 90% stronger etc.": "乘数 1 强 10%，乘数 9 强 90% 等等。",
    "Multiplier cost scalings are reduced.": "乘数成本比例降低。",
    "Multiplier Milestone rate is lowered by 10%.": "乘数里程碑率降低 10%。",
    "Multiplier Milestones are 10% more effective.": "倍增里程碑的效果提高了 10%。",
    "Multiplier Milestones:": "乘数里程碑：",
    "Multiplier Prestiges": "乘数声望",
    "Multiplier Prestiges also boost Multipliers.": "乘数声望也会提升乘数。",
    "Multiplier Prestiges' formula to Number gain is further improved. The upgrade to the left is required for this to take effect.": "Multiplier Prestiges的数字增益公式得到进一步改进。需要升级到左侧才能生效。",
    "Multiplier Prestiges' formula to Number gain is improved. The upgrade to the right will work.": "Multiplier Prestiges 的数字增益公式得到改进。向右升级将起作用。",
    "Multipliers": "乘数",
    "Multipliers are more effective proportinate to the total time played.": "乘数与所玩的总时间成比例更有效。",
    "Multipliers are stronger based on their tier.": "乘数根据其等级而更强。",
    "no": "不",
    "Notation:": "符号：",
    "Number growth is raised to the 1.05.": "人数增长上调至1.05。",
    "of a Multiplier": " 乘数",
    "Product for": "产品",
    "Products": "产品",
    "Records": "记录",
    "Reset your Game": "重置你的游戏",
    "so far.": "至今。",
    "Sorry, but the save file is not valid. Please import a valid save file.": "抱歉，保存文件无效。请导入有效的存档文件。",
    "sqrt(Days)+1": "sqrt(天)+1",
    "The amount of all Multipliers you own benefits Number gain.": "您拥有的所有乘数的数量会受益于数字增益。",
    "The current Multiplier Milestone significantly buffs Number production.": "当前的乘数里程碑显着增强了数字生产。",
    "This Multiplier Prestige run has taken": "此乘数声望轮数已花费了",
    "This Product run has taken": "此产品运行已占用",
    "Tick Interval:": "Tick间隔：",
    "Times": "时间",
    "to Number gain)": "数增益）",
    "translating\n        to a": "将\n 转换为",
    "Unlock an effect of Factored Points multiplying all Multipliers. [FOREVER]": "解锁因子点乘以所有乘数的效果。 [永远]",
    "Use with caution. You will lose your local save forever! It is recommended\n          to export and store your save somewhere first before doing this, unless you are sure you want to\n          start over.": "谨慎使用。您将永远失去本地存档！建议\n 在执行此操作之前先导出并存储您的存档，除非您确定要\n 重新开始。",
    "Version:": "版本：",
    "x every": "x 每",
    "x multiplier to all Multipliers": "x 乘数到所有乘数",
    "You Are About to Import a Save.": "您即将导入存档。",
    "YOU ARE ABOUT TO RESET YOUR PROGRESS ON THIS GAME.": "您即将重置您在此游戏中的进度。",
    "You have gained": "你获得了",
    "You have played for": "你玩了",
    "You have produced a total Number of": "您总共产生了",
    "Your fastest Product run took": "您最快的产品运行时间",
    "Engineering": "工程",
    "Logarithmic": "对数",
    "Long Alphabetic": "长字母",
    "Multiplicative": "乘法",
    "Standard": "标准",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "ms": "ms",
    "FP": "FP",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^e([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) c$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You start runs with (.+) Multiplier Prestiges.$/, '您以 $1 声望乘数开始新的一轮。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) hours and ([\d\.]+) minutes$/, '$1 小时 $2 分'],
    [/^([\d\.]+) hours, ([\d\.]+) minutes and ([\d\.]+) second$/, '$1 小时 $2 分 $3 秒'],
    [/^([\d\.]+) hours, ([\d\.]+) minutes and ([\d\.]+) seconds$/, '$1 小时 $2 分 $3 秒'],
    [/^([\d\.]+) minutes and ([\d\.]+) second$/, '$1 分 $2 秒'],
    [/^([\d\.]+) minutes and ([\d\.]+) seconds$/, '$1 分 $2 秒'],
    [/^([\d\.]+) minutes$/, '$1 分'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Factored Points$/, '$1 因子点数'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^FP\+([\d\.,]+)$/, 'FP\+$1'],
    [/^Buy ([\d\.,]+) for$/, '购买 $1 花费'],
    [/^Multiplier ([\d\.,]+)$/, '乘数 $1'],
    [/^Costs ([\d\.,]+) FP$/, '成本 $1 FP'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);